=== 2307856559/hasor/Trunk/examples/第一部分：入门教程/More_JDBC/beans-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- beans标签 -->
	<xs:element name="beans">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="bean" type="element_bean_Type" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="staticCache" type="xs:integer" default="10"/>
			<xs:attribute name="dynamicCache" type="xs:integer" default="50"/>
		</xs:complexType>
	</xs:element>
	<!-- ================================================================================================================ -->
	<!-- bean标签 -->
	<xs:complexType name="element_bean_Type">
		<xs:sequence>
			<xs:element name="factoryConfig" type="element_factoryConfig_Type" minOccurs="0"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="constructor-arg" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="meta" type="element_meta_Type"/>
							<xs:group ref="prop_element_grout"/>
						</xs:choice>
						<xs:attributeGroup ref="att_prop"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="meta" type="element_meta_Type" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="property" type="element_property_Type" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="addImpl" type="element_addImpl_Type" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" default="beanID_0"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="singleton" type="xs:boolean" default="true"/>
		<xs:attribute name="iocType" default="Ioc">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Ioc"/>
					<xs:enumeration value="Fact"/>
					<xs:enumeration value="Export"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="export-refBean" type="xs:string"/>
		<xs:attribute name="lazyInit" type="xs:boolean" default="true"/>
		<xs:attribute name="aopFilters-refBean" type="xs:string" default="xxx,xxx,xxx"/>
	</xs:complexType>
	<!-- ================================================================================================================ -->
	<!-- meta标签 -->
	<xs:complexType name="element_meta_Type">
		<xs:attribute name="key" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- ================================================================================================================ -->
	<!-- factoryConfig标签 -->
	<xs:complexType name="element_factoryConfig_Type">
		<xs:sequence>
			<xs:element name="methodParam" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="meta" type="element_meta_Type" minOccurs="0" maxOccurs="unbounded"/>
						<xs:group ref="prop_element_grout"/>
					</xs:choice>
					<xs:attributeGroup ref="att_prop"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="refBean" type="xs:string" use="required"/>
		<xs:attribute name="isStaticMethod" type="xs:boolean" default="true"/>
		<xs:attribute name="methodName" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- ================================================================================================================ -->
	<!-- property标签 -->
	<xs:complexType name="element_property_Type">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="meta" type="element_meta_Type"/>
			<xs:group ref="prop_element_grout"/>
		</xs:choice>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="refValue" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	<!-- ================================================================================================================ -->
	<!-- addImpl标签 -->
	<xs:complexType name="element_addImpl_Type">
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="refType" type="xs:string"/>
		<xs:attribute name="delegate-refBean" type="xs:string"/>
	</xs:complexType>
	<!-- ================================================================================================================ -->
	<!--【构造方法、属性、工厂方法、value】共同部分-->
	<xs:attributeGroup name="att_prop">
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="refValue" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
	</xs:attributeGroup>
	<!-- ================================================================================================================ -->
	<xs:group name="prop_element_grout">
		<xs:choice>
			<xs:element name="value" type="element_value_Type"/>
			<xs:element name="array" type="element_array_Type"/>
			<xs:element name="list" type="element_list_Type"/>
			<xs:element name="set" type="element_set_Type"/>
			<xs:element name="map" type="element_map_Type"/>
		</xs:choice>
	</xs:group>
	<!-- ================================================================================================================ -->
	<xs:complexType name="element_value_Type" mixed="true">
		<xs:attributeGroup ref="att_prop"/>
	</xs:complexType>
	<xs:complexType name="element_array_Type">
		<xs:group ref="prop_element_grout" minOccurs="0" maxOccurs="unbounded"/>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="element_list_Type">
		<xs:group ref="prop_element_grout" minOccurs="0" maxOccurs="unbounded"/>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="element_set_Type">
		<xs:group ref="prop_element_grout" minOccurs="0" maxOccurs="unbounded"/>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="element_map_Type">
		<xs:choice>
			<xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:all>
						<xs:element name="mapKey">
							<xs:complexType>
								<xs:group ref="prop_element_grout" minOccurs="0" maxOccurs="unbounded"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="mapVar">
							<xs:complexType>
								<xs:group ref="prop_element_grout" minOccurs="0" maxOccurs="unbounded"/>
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== 2307856559/hasor/Releases/more_1.0.0.20100126_alpha3/examples/第一部分：入门教程/MoreBeans/more-config.xml
<beans staticCache="10" dynamicCache="50"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="beans-schema.xsd"
	xsi:schemaLocation="http://more.byshell.org/schema/anno anno-schema.xsd"
	xmlns:anno="http://more.byshell.org/schema/anno">

	<!-- 开启注解配置-->
	<anno:anno package="org.moretest.beans.*" />

	<!-- 基本类型Bean，String -->
	<bean name="base_String" type="java.lang.String">
		<constructor-arg type="String" value="测试字符串" />
	</bean>
	<bean name="base_Boolean" type="java.lang.Boolean">
		<constructor-arg type="String" value="true" />
	</bean>

	<!-- 最简单Bean配置 -->
	<bean name="xmlBean" type="org.moretest.beans._1_simple.XmlSimpleBean" />

	<!-- 单态配置，默认所有bean都是单态配置  -->
	<bean name="xmlSingletonBean" type="org.moretest.beans._2_singleton.XmlSingletonBean" singleton="false" />

	<!-- 延迟初始化，默认所有bean都是延迟的 -->
	<bean name="xmlLazyBean" type="org.moretest.beans._3_lazy.XmlLazyBean" lazyInit="false" />

	<!-- 构造方法注入创建Bean -->
	<bean name="xmlSimpleConstructorBean" type="org.moretest.beans._4_constructor.XmlSimpleConstructorBean">
		<constructor-arg type="int" value="123" />
		<constructor-arg type="float" value="3.14" />
		<constructor-arg type="String" value="测试字符串" />
	</bean>
	<bean name="xmlRefConstructorBean" type="org.moretest.beans._4_constructor.XmlRefConstructorBean">
		<constructor-arg type="org.moretest.beans._1_simple.XmlSimpleBean" refValue="xmlBean" />
	</bean>

	<!-- 基本数据类型注入 -->
	<bean name="xmlBaseTypeBean" type="org.moretest.beans._5_basetype.XmlBaseTypeBean">
		<property name="booleanData" type="boolean" value="true" />
		<property name="byteData" type="byte" value="123" />
		<property name="shortData" type="short" value="789" />
		<property name="intData" type="int" value="-1245" />
		<property name="longData" type="long" value="89898989" />
		<property name="floatData" type="float" value="235.65" />
		<property name="doubleData" type="double" value="-3.141592653" />
		<property name="stringData" type="String" value="测试字符串数据" />
	</bean>

	<!-- 四种引用类型注入 -->
	<bean name="xmlRefBean" type="org.moretest.beans._6_ref.XmlRefBean">
		<meta key="msg" value="附带的甜点信息字符串" />
		<!-- $Bean的附带信息作为注入数据。该类型信息只能是String类型 -->
		<property name="metaData" type="String" refValue="{$msg}" />
		<!-- 普通引用注入 -->
		<property name="xmlSimpleBean" type="org.moretest.beans._1_simple.XmlSimpleBean" refValue="xmlBean" />
		<!--@0意在在执行getBean()时候第二个附带参数数组中将下标为0的对象作为数据注入-->
		<property name="paramData" type="java.lang.Object" refValue="{@0}" />
		<!--#this意在将ioc容器BeanFactory作为数据注入-->
		<property name="beanFactory" type="org.more.beans.BeanFactory" refValue="{#this}" />
		<!--#apple意在将ioc容器BeanFactory中属性名称为apple的数据注入-->
		<property name="contextData" type="java.lang.Object" refValue="{#apple}" />
	</bean>

	<!-- 大文本注入的方式 -->
	<bean name="xmlBigStringBean_1" type="org.moretest.beans._7_bigstring.XmlBigStringBean">
		<property name="bigString" type="String">
			<!-- 注意CDATA标记与value标签之间应当紧凑否则可能注入错误的数据。 -->
			<value><![CDATA[id="" value="12" refValue="refBean|{#attName}|{@number}|{$mime}" type="int|byte|char|double|float|long|short|boolean|String"
id="" refValue="refBean|{#attName}|{@number}|{$mime}" type="int|byte|char|double|float|long|short|boolean|String"]]></value>
		</property>
	</bean>
	<bean name="xmlBigStringBean_2" type="org.moretest.beans._7_bigstring.XmlBigStringBean">
		<property name="bigString" type="String">
			<value>注意CDATA标记与value标签之间应当紧凑否则可能注入错误的数据。</value>
		</property>
	</bean>

	<!-- 一维数组类型注入(目前不支持二维数组) -->
	<bean name="xmlArrayBean" type="org.moretest.beans._8_array.XmlArrayBean">
		<meta key="msg" value="附带在Bean上" />
		<property name="intArray" type="int">
			<array>
				<value value="1" />
				<value value="2" />
				<value value="3" />
				<value value="4" />
			</array>
		</property>
		<property name="stringArray" type="String">
			<meta key="msg" value="附带的甜点信息字符串" />
			<array>
				<value value="字符串1" />
				<value type="String" refValue="{@0}" />
				<value refValue="base_String" />
				<value refValue="{$msg}" />
			</array>
		</property>
		<property name="objectArray" type="org.moretest.beans._1_simple.XmlSimpleBean">
			<array>
				<value refValue="xmlBean" />
				<value refValue="xmlBean" />
			</array>
		</property>
	</bean>
	<bean name="xmlConstructorArrayBean" type="org.moretest.beans._8_array.XmlConstructorArrayBean">
		<meta key="msg" value="附带在Bean上" />
		<constructor-arg type="int">
			<array>
				<value value="1" />
				<value value="2" />
				<value value="3" />
				<value value="4" />
			</array>
		</constructor-arg>
		<constructor-arg type="String">
			<meta key="msg" value="附带的甜点信息字符串" />
			<array>
				<value value="字符串1" />
				<value type="String" refValue="{@0}" />
				<value refValue="base_String" />
				<value refValue="{$msg}" />
			</array>
		</constructor-arg>
		<constructor-arg type="org.moretest.beans._1_simple.XmlSimpleBean">
			<array>
				<value refValue="xmlBean" />
				<value refValue="xmlBean" />
			</array>
		</constructor-arg>
	</bean>

	<!-- List类型的注入 -->
	<bean name="xmlListBean" type="org.moretest.beans._9_collection.XmlListBean">
		<!-- 要注入的目标对象属性类型 -->
		<property name="objectList" type="java.util.List">
			<!-- 具体实例化的类型 -->
			<list type="java.util.LinkedList">
				<value type="String" value="测试字符数据" />
				<value refValue="xmlBigStringBean_1" />
			</list>
		</property>
	</bean>
	
	<!-- Map类型的注入 -->
	<bean name="xmlMapBean" type="org.moretest.beans._9_collection.XmlMapBean">
		<property name="objectMap" type="java.util.Map">
			<map type="java.util.Hashtable">
				<entry>
					<mapKey>
						<value type="String" value="xmlBaseTypeBean" />
					</mapKey>
					<mapVar>
						<value refValue="xmlBaseTypeBean" />
					</mapVar>
				</entry>
				<entry>
					<mapKey>
						<value refValue="xmlBean" />
					</mapKey>
					<mapVar>
						<value refValue="xmlSimpleConstructorBean" />
					</mapVar>
				</entry>
			</map>
		</property>
	</bean>

	<!-- Set类型的注入 -->
	<bean name="xmlSetBean" type="org.moretest.beans._9_collection.XmlSetBean">
		<property name="objectSet" type="java.util.Set">
			<set type="java.util.LinkedHashSet">
				<value type="String" value="测试字符数据" />
				<value refValue="xmlRefBean" />
			</set>
		</property>
	</bean>

	<!-- AOP配置，xmlSimpleAopBean Bean配置了两个拦截器 -->
	<bean name="xmlAopFilterBean_1" type="org.moretest.beans._a_aop.XmlAopFilterBean" />
	<bean name="xmlAopFilterBean_2" type="org.moretest.beans._a_aop.XmlAopFilterBean" />
	<bean name="xmlSimpleAopBean" type="org.moretest.beans._a_aop.XmlSimpleAopBean" aopFilters-refBean="xmlAopFilterBean_1,xmlAopFilterBean_2"/>

	<!-- 附加接口实现 -->
	<bean name="xmlUserFace1" type="org.moretest.beans._b_impl.XmlUserFace1" /><!-- 要附加的接口1 -->
	<bean name="xmlImplDelegate" type="org.moretest.beans._b_impl.XmlImplDelegate" /><!-- 接口代理 -->
	<bean name="xmlImplBean" type="org.moretest.beans._b_impl.XmlImplBean">
		<addImpl refType="xmlUserFace1" delegate-refBean="xmlImplDelegate" />
		<addImpl type="org.moretest.beans._b_impl.XmlUserFace2" delegate-refBean="xmlImplDelegate" />
	</bean>
</beans>

=== 2307856559/hasor/examples/第二部分：中级教程/Filter/src/more-config.xml
<beans staticCache="10" dynamicCache="50"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="beans-schema.xsd"
	xsi:schemaLocation="http://more.byshell.org/schema/anno anno-schema.xsd"
	xmlns:anno="http://more.byshell.org/schema/anno">

	<bean name="filter" type="org.moretest.filter.TestFilter">
		<meta key="isFilter" value="true"/>
	</bean>
	<bean name="publicFilter" type="org.moretest.filter.PublicFilter">
		<meta key="isFilter" value="true"/>
		<meta key="isPublicFilter" value="true"/>
	</bean>
	
	<bean name="action" type="org.moretest.filter.TestAction">
		<meta key="isAction" value="true" />
		<meta key="actionFilters" value="filter" />
	</bean>
	<bean name="action-filterLink" type="org.moretest.filter.TestAction">
		<meta key="isAction" value="true" />
		<meta key="actionFilters" value="filter,filter" />
	</bean>
</beans>

=== 2307856559/hasor/Release branches/more_1.x/examples/第二部分：中级教程/Filter/more-config.xml
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="beans-schema.xsd">
	<bean name="filter" type="org.moretest.filter.TestFilter" />
	<bean name="publicFilter" type="org.moretest.filter.PublicFilter">
		<meta key="isPublicFilter" value="true"/>
	</bean>
	
	
	<bean name="action" type="org.moretest.filter.TestAction">
		<meta key="isAction" value="true" />
		<meta key="actionFilters" value="filter" />
	</bean>
	<bean name="action-filterLink" type="org.moretest.filter.TestAction">
		<meta key="isAction" value="true" />
		<meta key="actionFilters" value="filter,filter" />
	</bean>
</beans>

=== 2307856559/hasor/examples/第一部分：入门教程/More_JDBC/more-config.xml
<beans staticCache="10" dynamicCache="50"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="beans-schema.xsd"
	xsi:schemaLocation="http://more.byshell.org/schema/anno anno-schema.xsd"
	xmlns:anno="http://more.byshell.org/schema/anno">

	<!-- c3p0数据源 -->
	<bean name="sys_databaseSource" type="com.mchange.v2.c3p0.ComboPooledDataSource">
		<property name="driverClass" type="String" value="net.sourceforge.jtds.jdbc.Driver"/>
		<property name="jdbcUrl" type="String" value="jdbc:jtds:sqlserver://127.0.0.1:1433;databasename=test"/>
		<property name="user" type="String" value="sa"/>
		<property name="password" type="String" value="sa"/>
		<property name="maxPoolSize" type="int" value="500" />
		<property name="minPoolSize" type="int" value="10" />
		<property name="initialPoolSize" type="int" value="1" />
		<property name="maxIdleTime" type="int" value="10" />
	</bean>
	<!-- jdbc事务控制拦截器 -->
	<bean name="sys_transactionManager" type="org.more.dao.jdbc.JdbcTransactionManager">
		<property name="dataSource" refValue="sys_databaseSource" type="javax.sql.DataSource"/>
		<property name="autoCommit" type="boolean" value="false"/>
	</bean>
	
	
	<!-- Action中使用jdbc -->
	<bean name="testJDBCAction" type="org.console.JDBCAction" aopFilters-refBean="sys_transactionManager">
		<meta key="isAction" value="true"/>
	</bean>
	<!-- 业务层使用jdbc -->
	<bean name="jobJDBC" type="org.console.JobJDBC" aopFilters-refBean="sys_transactionManager"/>
	<bean name="testJobAction" type="org.console.JobAction">
		<property name="jobJDBC" refValue="jobJDBC" type="org.console.JobJDBC"/>
		<meta key="isAction" value="true"/>
	</bean>



	<!-- 不具备事务管理的 -->
	<bean name="testJDBC_2" type="org.console.JDBCAction">
		<property name="dataSource" refValue="sys_databaseSource" type="javax.sql.DataSource"/>
		<meta key="isAction" value="true"/>
	</bean>
</beans>
